/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YsAvatar: typeof import('@ys/components/composite/avatar')['default']
    YsButton: typeof import('@ys/components/composite/button')['default']
    YsCard: typeof import('@ys/components/composite/card')['default']
    YsResizablePanel: typeof import('@ys/components/composite/resizable-panel')['default']
    YsTooltip: typeof import('@ys/components/composite/tooltip')['default']
  }
}
